### ISSUE TITLE
Improve Wolf Navigation Behavior

### ISSUE THREAD

**Issue by Polytonic** [ludimation/Winter#7]
So as we discovered during Wednesday's demo, the wolf navigation behavior is still bugged.  Unfortunately, only Ryan here has a Unity Pro License.  

I think this is a two-step solution. 
1.  Improve some of the nav mesh characteristics (perhaps reduce angle to 25° to get an even flatter surface)? 
2.  Tweak some of the wolf behavior by giving it a predetermined set of coordinates to go to, rather than generating them at random.  Maybe @diokatsu can handle this part?

**Comment by ludimation** [comment]
I have nothing to contribute on the code side, unfortunately. But I DID
want to say that I appreciate you guys putting some effort into looking
into this. I have set up two display laptops for the game with external
monitors. Please let me know what the most stable version of the build
should be and I'll make sure it gets onto the two laptops.

Are you guys working in Sage together, by the way? Call me if you're all
hanging out because I'd love to join you!

**Comment by Polytonic** [comment]
I'm pretty sure that the problem now stems from the random point generation placing a destination within the mountain.
